### ISSUE TITLE
right to left slide

### ISSUE THREAD

**Issue by hanie-hadadi** [juanbrujo/jQuery-Timelinr#10]
how can i change direction of the horizontal sliding ? change to right to left instead of left to right , is there any option?

**Comment by juanbrujo** [comment]
yes @hanie-hadadi :

```
autoPlayDirection: 'forward' // value: forward | backward, default to forward
```

**Comment by hanie-hadadi** [comment]
i want to use arrowKeys: 'true'
what can i do now?

**Comment by juanbrujo** [comment]
@hanie-hadadi I don't get it, you can use arrowKeys and autoplay backwards. What's the problem?

**Comment by juanbrujo** [comment]
closing due long time of inactivity
