### ISSUE TITLE
change height of divs to accomdodate more copy in verticle timeline

### ISSUE THREAD

**Issue by creat1vemissy** [juanbrujo/jQuery-Timelinr#14]
I am trying to implement this timeline, but run into an issue when the copy gets long, and it gets cut off. 
ss attached
![screenshot](https://cloud.githubusercontent.com/assets/5656782/12729188/77a81dce-c8f3-11e5-8030-72b83828063c.jpg)

**Comment by juanbrujo** [comment]
OK I see the problem. Maybe a simple solution is to add via CSS `overflow-y: auto` to the text/content container so if it is larger than the timeline itself, a scroll will be shown.

**Comment by creat1vemissy** [comment]
thank you!
