### ISSUE TITLE
I would like the first image to animate, but the animation doesn't begin until slide 2.

### ISSUE THREAD

**Issue by creat1vemissy** [juanbrujo/jQuery-Timelinr#15]
How do I do this?

I would like the first image to animate, but the animation doesn't begin until slide 2.

http://www.hgtc.edu/about_hgtc/50/timeline.html

See the example link in the body of the page.

thanks!

**Comment by juanbrujo** [comment]
why do you have `startAt: 2`? if you remove that the timeline will start at the first *issue* and the first image should be animated.

**Comment by creat1vemissy** [comment]
Hi Juan-  It does not animate the first image for some reason.  Can you help?  I have switched it back to begin at 1

**Comment by creat1vemissy** [comment]
the timeline link is on the right hand nav here:

http://www.hgtc.edu/about_hgtc/50/  See timeline of events.

**Comment by creat1vemissy** [comment]
Were you able to view this Juan?

**Comment by juanbrujo** [comment]
@creat1vemissy remove from the first `<li id="1960" class="selected">` the ` class="selected"` so let jQuery Timelinr inject that class for you. That should be the trick.

**Comment by creat1vemissy** [comment]
Nice- thank you so much!  =)
