### ISSUE TITLE
marginTop of #issues is overridden and prevent sliding

### ISSUE THREAD

**Issue by bluantinoo** [juanbrujo/jQuery-Timelinr#22]
I'm using the vertical version of the plugin inside a Builder of a Wordpress website.
The builder css overwrites the assigned marginTop on #issues preventing the sliding up/down.

you should add **important!** in some way to the marginTop or marginLeft values assigned by the script.

**Comment by juanbrujo** [comment]
@bluantinoo I don't think it's a good idea to add `!important` to the script style just because an external script/tool interferes with it. It's not Timelinr fault, but your WordPress Builder.
