### ISSUE TITLE
Getting Error: TypeError: $(...).timelinr is not a function

### ISSUE THREAD

**Issue by kbdavis07** [juanbrujo/jQuery-Timelinr#6]
Error: TypeError: $(...).timelinr is not a function

When using Jquery 2.1 get the error 

But goes away when using Jquery 1.7.2

**Comment by maulikvora** [comment]
Hi @juanbrujo is version 1.0 ready?

Hi @kbdavis07 I am using jquery 2.1.1 and I need to use this plugin which requires jQuery 1.7.2,
how should I use jquery-migrate plugin to allow both versions on my page. Please suggest.

**Comment by juanbrujo** [comment]
@maulikvora In my tests, the current -stable- version of Timelinr works 'till jQuery-2.1.3 with and without migrate add-on.

**Comment by maulikvora** [comment]
Ok Thanks @juanbrujo I will retest, may be there is another problem in my code. Will update you.
