### ISSUE TITLE
Slider does not reset waiting time and keeps running counter with setInterval

### ISSUE THREAD

**Issue by mangeshn** [juanbrujo/jQuery-Timelinr#8]
There is one issue with slide wait delay. I set "autoPlayPause" to 5000 miliseconds and it works fine initially, but when i click on next or random slide then it takes 1 second to move slide and after this action current slide remains there for 3-4 seconds only instead of 5 seconds.

Can you please let us know about how to reset delay time, and i think issue is with setTimeinterval.

**Comment by juanbrujo** [comment]
done in https://github.com/juanbrujo/jQuery-Timelinr/releases/tag/v0.9.7
